import 'package:audioplayers/audioplayers.dart';
import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

/// The app's sound effects. Files live in `assets/sfx/` and are generated by
/// `tool/generate_sfx.py` — replace any of them with your own recording of the
/// same name and nothing else has to change.
enum Sfx {
  /// A chip landing on the felt.
  chip('chip.wav'),

  /// A card sliding out of the shoe.
  card('card.wav'),

  /// A control being pressed.
  button('button.wav'),

  win('win.wav'),
  lose('lose.wav'),
  push('push.wav'),
  blackjack('blackjack.wav');

  const Sfx(this.file);
  final String file;

  String get asset => 'sfx/$file';
}

/// Plays short interface sounds.
///
/// Every call is fire-and-forget and swallows its own errors: audio is a
/// nicety, and a device that cannot play it must still deal cards. Nothing
/// happens at all until [load] has run, so tests and the pure game logic never
/// touch a platform channel.
class SoundService {
  const SoundService._();

  static const _kEnabled = 'sfx_enabled';

  /// How many sounds can overlap before the oldest is cut off. A deal fires
  /// several card sounds in quick succession, so this needs a little room.
  static const _voices = 4;

  static final List<AudioPlayer> _pool = [];
  static int _next = 0;
  static bool _ready = false;
  static bool _enabled = true;

  /// Whether sound effects are switched on.
  static bool get enabled => _enabled;

  /// Swappable so tests can assert what would have played without any audio.
  @visibleForTesting
  static void Function(Sfx)? playerOverride;

  /// Read the saved preference and warm up the players. Safe to call twice.
  static Future<void> load() async {
    try {
      final prefs = await SharedPreferences.getInstance();
      _enabled = prefs.getBool(_kEnabled) ?? true;
    } catch (_) {
      _enabled = true;
    }
    if (_ready || playerOverride != null) return;
    try {
      for (var i = 0; i < _voices; i++) {
        final player = AudioPlayer()
          ..setReleaseMode(ReleaseMode.stop)
          ..setPlayerMode(PlayerMode.lowLatency);
        _pool.add(player);
      }
      _ready = true;
    } catch (error) {
      debugPrint('Sound unavailable: $error');
      _ready = false;
    }
  }

  static Future<void> setEnabled(bool value) async {
    _enabled = value;
    try {
      final prefs = await SharedPreferences.getInstance();
      await prefs.setBool(_kEnabled, value);
    } catch (_) {
      // A preference we cannot persist is not worth failing over.
    }
    if (value) play(Sfx.button); // let the player hear what they just enabled
  }

  /// Play [sound]. Never throws, never awaits the caller.
  static void play(Sfx sound) {
    if (!_enabled) return;
    final override = playerOverride;
    if (override != null) {
      override(sound);
      return;
    }
    if (!_ready || _pool.isEmpty) return;
    final player = _pool[_next % _pool.length];
    _next++;
    // Deliberately not awaited: a card should never wait on a speaker.
    player.play(AssetSource(sound.asset)).catchError((Object error) {
      debugPrint('Sound failed (${sound.file}): $error');
    });
  }

  @visibleForTesting
  static void resetForTest() {
    playerOverride = null;
    _enabled = true;
    _next = 0;
  }
}
