"""Write test/fixtures/strategy_reference.dart from reference_charts.json.

reference_charts.json was scraped on 2026-09-28 from the blackjackinfo.com
basic strategy engine (peek, every rule combination the app ships) with
fetch_reference.sh + parse_bji.py. Codes: H hit, S stand, D double else hit,
d double else stand, P split, R surrender else hit, r surrender else stand,
p surrender else split.
"""
import json, os

here = os.path.dirname(os.path.abspath(__file__))
db = json.load(open(os.path.join(here, 'reference_charts.json')))
out = [
    '// GENERATED by tool/strategy_check/export_fixture.py — do not edit.',
    '//',
    '// Basic strategy charts from the blackjackinfo.com strategy engine,',
    '// fetched 2026-09-28 for every rule combination the app can deal. Keys:',
    '// d<decks>_<h17|s17>_das<yes|no>_<all|d9|d10>_<ns|ls>.',
    '// Hard rows 5..17 then 18+, soft rows A,2..A,9, pair rows 2,2..A,A;',
    '// columns dealer 2..10, A. H hit, S stand, D double/hit, d double/stand,',
    '// P split, R surrender/hit, r surrender/stand, p surrender/split.',
    '',
    'const strategyReference = <String, Map<String, List<String>>>{',
]
for key in sorted(db):
    v = db[key]
    out.append(f"  '{key}': {{")
    for name, label in [('hard', 'Hard Totals'), ('soft', 'Soft Totals'), ('pairs', 'Pairs')]:
        rows = ', '.join(f"'{''.join(a)}'" for _, a in v[label])
        out.append(f"    '{name}': [{rows}],")
    out.append('  },')
out.append('};')
open(os.path.join(here, '..', '..', 'test', 'fixtures', 'strategy_reference.dart'), 'w').write('\n'.join(out) + '\n')
print('wrote', len(db), 'charts')
